### ISSUE TITLE
Empty search broken

### ISSUE THREAD

**Issue by schliflo** [conexco/shopware-bootstrap-theme#11]
Doing an empty search `/search?sSearch=` leads to a smarty error.  This does not happen with the Responsive theme.
![empty-search-bootstrap](https://user-images.githubusercontent.com/9881672/32336511-c9689ee6-bfef-11e7-9239-9fc11e23403f.png)
![empty-search-responsive](https://user-images.githubusercontent.com/9881672/32336517-cc3886e0-bfef-11e7-869f-92e3d0c373e0.png)

`Fatal error: Uncaught Error: Call to a member function getLimit() on null in /app/var/cache/development_7c271db/templates/frontend_BootstrapExtension_de_DE_3/0d/43/a6/0d43a66b54ef66410de5ae1870e7932083d651a2.snippet.index.tpl.php:543 Stack trace: #0 /app/engine/Library/Smarty/sysplugins/smarty_internal_templatebase.php(180): content_59fb402243d916_08546992(Object(Enlight_Template_Default)) #1 /app/engine/Library/Enlight/View/Default.php(276): Smarty_Internal_TemplateBase->fetch() #2 /app/engine/Library/Enlight/Controller/Plugins/ViewRenderer/Bootstrap.php(216): Enlight_View_Default->render(Object(Enlight_Template_Default)) #3 /app/engine/Library/Enlight/Controller/Plugins/ViewRenderer/Bootstrap.php(242): Enlight_Controller_Plugins_ViewRenderer_Bootstrap->renderTemplate(Object(Enlight_Template_Default)) #4 /app/engine/Library/Enlight/Controller/Plugins/ViewRenderer/Bootstrap.php(136): Enlight_Controller_Plugins_ViewRenderer_Bootstrap->render() #5 /app/engine/Library/Enlight/Event/Handler/Default.php(91): Enlight_Controller in /app/var/cache/development_7c271db/templates/frontend_BootstrapExtension_de_DE_3/0d/43/a6/0d43a66b54ef66410de5ae1870e7932083d651a2.snippet.index.tpl.php on line 543`

**Comment by benjamin-ott** [comment]
Thank you for your contribution. I just fixed that.
