### ISSUE TITLE
Strange animation when going below 768px breakpoint

### ISSUE THREAD

**Issue by schliflo** [conexco/shopware-bootstrap-theme#13]
Happens for example when rotating a Nexus 7 Tablet from landscape to portrait.
I guess this gif describes the issue best:
![nov-02-2017 17-15-58](https://user-images.githubusercontent.com/9881672/32337236-b586bbe0-bff1-11e7-9deb-bd0e035cd203.gif)

**Comment by benjamin-ott** [comment]
Thank you for your help. I refactored the main navigation and the offcanvas in a11100d.
