### ISSUE TITLE
Wrong content in checkout/finish

### ISSUE THREAD

**Issue by dennisirmscher** [conexco/shopware-bootstrap-theme#24]
I'm using the latest version of your theme and am facing an issue on the `frontend/checkout/finish.tpl`.

The template of this page extends the one from the `frontend/checkout/confirm.tpl`. And for whatever reason the main-conent-bock of the `confirm.tpl` `frontend_index_content` is still included in the finish-page prior to it's own content, although it should be overwritten in the `finish.tpl` as there is no `apend` or `$smarty.block.parent` in https://github.com/conexco/shopware-bootstrap-theme/blob/1.2/Resources/Themes/Frontend/BootstrapBare/frontend/checkout/finish.tpl#L45.

Even if I leave the content block completely empty in `finish.tpl` only the content of this one is missing while the one of the `confirm.tpl` is still being rendered. I have no idea why this is happening. Do you have any clue for me?

**Comment by dennisirmscher** [comment]
PS: Shopware version is 5.3.7

**Comment by benjamin-ott** [comment]
Hi, same as you i'm using BootstrapTheme 1.2.0 and Shopware 5.3.7 and i don't have any problems with the finish template.
The only explanation i can think about is that some other plugin is extending the block and causing the problem. Do you have anything else installed? Maybe it would help to switch them all off one by one.

**Comment by dennisirmscher** [comment]
You are right. Seem's like this is caused by Shopwares own B2B-Suite. I have not expected that to be honest. Sorry for bothering you and thank you for your quick reply! I'll get in touch with Shopware about the issue.
