### ISSUE TITLE
Fehler beim kompilieren

### ISSUE THREAD

**Issue by csaeum** [conexco/shopware-bootstrap-theme#25]
System:
Shopware 5.4.0
Amazon Payments 4.4.5

Fehler beim kompilieren des Themes:

Es ist ein Fehler aufgetreten
Während der Bearbeitung von Shop "Shop" ist ein Fehler aufgetreten: variable @font-base-stack is undefined in file /home/xxxx/www.xx.xx/engine/Shopware/Plugins/Community/Frontend/BestitAmazonPay/Views/frontend/_public/src/less/_modules/amazon-main.less in amazon-main.less on line 28, column 18 26| left: 50%; 27| 28| font-family: @font-base-stack; 29| 30| .border-radius(); 31| .unitize(font-size, @font-size-base);

**Comment by uehler** [comment]
@benjamin-ott @cxo-mayo @pkapowers looks like it could be fixed with a simple fallback to @swf-font-family-sans-serif or @swf-font-family-base. What do you say?

**Comment by uehler** [comment]
@csaeum we made a change on the dev-branch. It should fix your problem.

**Comment by uehler** [comment]
ping @pkapowers

**Comment by pkapowers** [comment]
@csaeum We just added a fallback value onto the dev branch.
