### ISSUE TITLE
Kompabilität zu 5.4.2

### ISSUE THREAD

**Issue by vossmedien** [conexco/shopware-bootstrap-theme#27]
Hallo zusammen,
es wäre super, wenn ihr die Kompabilität auf 5.4.2 erhöhen könntest :-)
Aktuell kann man es nicht mehr aus dem Store herunterladen.

Lieben Dank!!

Grüßle,

Christian

**Comment by uehler** [comment]
hello @vossmedien,

sorry for the delayed answer.
Sadly we hadn't time to test the theme and make it compatible with the new shopware version.

But you can download it from github and change the compatibility. Please let us know if everything is working. You can fix issues with the new version if you want or just create issues. Would be very helpful.

**Comment by csaeum** [comment]
Wie schaut es aus mit der Kompatibiltät mit 5.4.6 aus?

**Comment by benjamin-ott** [comment]
Der dev Branch ist bereits zur Version 5.4.6 kompatibel und wird derzeit getestet.
Wenn das Testing und Bugfixing abgeschlossen ist werden wir zeitnah eine neue Version veröffentlichen.
Feedback zum Dev Branch nehmen wir sehr gerne entgegen.

**Comment by csaeum** [comment]
Ok dann teste ich es auch mal in meiner Umgebung mit Stripe Amazon usw.

**Comment by Ach1m9** [comment]
Ich kann es unter 5.4.6 nicht installieren. In der .zip befindet sich angeblich kein Plugin

**Comment by csaeum** [comment]
Wie geht es generell mit den Projekt weiter?
Klar das ihr als Agentur euch nicht zu 100% nur auf das Konzentrieren könnt. Aber gerade geht es ja wenig weiter und wir sind bei Shopware schon bei 5.5.x

**Comment by ropemakr** [comment]
@csaeum Das Projekt ist absichtlich als Open Source veröffentlicht worden, so dass jeder der sich einbringen möchte dies auch tun kann. Wir als Agentur unterstützen dies im Rahmen unserer Möglichkeiten und nach Bedarf.
