### ISSUE TITLE
Incompatible with 5.4

### ISSUE THREAD

**Issue by TheMostTerrifying** [conexco/shopware-bootstrap-theme#29]
Compatibility Error - Code: BinariesException-20
Any plans to make it compatible with 5.4 ?
Best Regards

**Comment by uehler** [comment]
Hi @TheMostTerrifying,

the theme is compatible with 5.4 and 5.4.1 and will be compatible with 5.4.2 and newer in the future.

Your error message sounds like an error with the installation zip file. Where did you get it from and which shopware version are you using?

**Comment by TheMostTerrifying** [comment]
Tried (and failed) to get it via the plugin-manager, I'm running 5.4.3.

**Comment by benjamin-ott** [comment]
duplicates #27
