### ISSUE TITLE
Exception in SW prior version 5.3.3

### ISSUE THREAD

**Issue by jmatthiesen81** [conexco/shopware-bootstrap-theme#3]
The container parameter "%active_plugins%" is available since the Shopware version  5.3.3.
But the minimum required shopware version is set to 5.3.0 in plugin.xml.

`<compatibility minVersion="5.3.0"/>`

https://github.com/shopware/shopware/blob/7c271dbfb62cdbbeab4a728d48d108c8f5d67ee4/UPGRADE-5.3.md#533

Installation of the bootstrap theme plugin in Shopware prior 5.3.3 ends up in an Exception with the error message:

> The service "swf_bootstrap_theme.subscribers.frontend" has a dependency on a non-existent parameter "active_plugins".

**Comment by uehler** [comment]
Thank you, I just fixed that
