### ISSUE TITLE
"not licensed" issue

### ISSUE THREAD

**Issue by retailify** [conexco/shopware-bootstrap-theme#30]
Hi everybody, 
I've installed the theme plugin as described in your docs in Shopware 5.4.3 and I'm getting following error.

![error](https://user-images.githubusercontent.com/5236353/40873405-c2d16cae-665f-11e8-919c-835e4c8c79cf.png)

Whats going on?

**Comment by uehler** [comment]
Hi @retailify,
looks like a Shopware problem. We don't have a license check implemented or activated.
Are you having any problems installing or using the theme?

**Comment by retailify** [comment]
Hi @uehler, 
no there are no problems at all with the theme. The error occurs in Shopware 5.4.3.
I've updated Shopware to 5.4.4 recently but the failure persist. 
Is your latest bootstrap release compatible with Shopware 5.4.3?

**Comment by uehler** [comment]
The theme is compatibel with shopware 5.4.0, but there is an untested branch "sw5.4.1-update" for shopware 5.4.1.
We will soon work on the compatibility for shopware 5.4.5

**Comment by benjamin-ott** [comment]
duplicates #27
