### ISSUE TITLE
Wishlist function isn't working anymore

### ISSUE THREAD

**Issue by thomasfrobieter** [conexco/shopware-bootstrap-theme#37]
Tested in article detail as well as lists. The wishlist link itself and the link in the header are updated correctly. After page reload or switching to the wishlist page, the wishlist is empty.

**Comment by thomasfrobieter** [comment]
Okay, we've figured out the cause. It's the super amazing cookie setting in the shopware backend ("Cookie-Hinweis-Modus" / "Cookie-Hint-Mode"). You have to set it to "Nur Hinweis anzeigen" ("just show hint" ..) the two other options will block the required cookie, so the wishlist stops working - even if cookies where already accepted by the user.

So .. this is probably a Shopware core bug?

**Comment by uehler** [comment]
hey @thomasfrobieter,

yes, that's a shopware bug/feature. You're basket shouldn't work either with that cookie setting.

Thanks for the feedback!
