### ISSUE TITLE
Exception in Category - tested on SW Demo 5.3.4

### ISSUE THREAD

**Issue by snHolst** [conexco/shopware-bootstrap-theme#4]
Fatal error: Uncaught Error: Call to a member function **getUserConditions() on null i**n /home/vagrant/www/shopware/var/cache/production____REVISION___/templates/frontend_BootstrapExtension_de_DE_1/7f/91/0d/7f910daf15c1e70c6418c8e89edd5e1df4183206.snippet.index.tpl.php on line 2223 ( ! ) Error: Call to a member function getUserConditions() on null in /home/vagrant/www/shopware/var/cache/production____REVISION___/templates/frontend_BootstrapExtension_de_DE_1/7f/91/0d/7f910daf15c1e70c6418c8e89edd5e1df4183206.snippet.index.tpl.php on line 2223 Call Stack #TimeMemoryFunctionLocation 10.0004362384{main}( ).../shopware.php:0... 

http://192.168.33.10/shopware/genusswelten/

**Comment by uehler** [comment]
Thank you @snHolst, i just fixed that

**Comment by snHolst** [comment]
nice!
