### ISSUE TITLE
UNMAINTAINED!! DO NOT USE THIS!

### ISSUE THREAD

**Issue by JPustkuchen** [conexco/shopware-bootstrap-theme#49]
Sorry but we've decided to use this project years ago and it's open source, so no offense ;) But the status is: No maintainer at all seems to care for it anymore. It was a very very expensive mistake!

It doesn't extend sw-Bare template (or it doesn't work) so all changes to bare have to be made manually also to this base theme. Each shopware update is HORROR.

I can only strongly suggest to NOT use this until there is an active maintainer or community perhaps one day again...  We lost several days in bugs and incompatibilities. None of our pull requests have ever been answered. Don't do it like us ;) ;)

**Comment by thomasfrobieter** [comment]
If someone from conexco still watches this thing: Please archive this project and add a warning to the description.

**Comment by uehler** [comment]
Hey guys,

we are still looking for a good solution to continue the work on the theme and keep the quality as high as possible
Meanwhile I will look into your pull requests and merge them.

Keep up your work, we are happy for all your pull requests!

**Comment by JPustkuchen** [comment]
Many thanks in advance for your effort, time and answer!
