### ISSUE TITLE
Registration is not working with shipping address

### ISSUE THREAD

**Issue by shyim** [conexco/shopware-bootstrap-theme#5]
The country select is missing in the registration. The config parameter CountryShipping does not exist
https://github.com/conexco/shopware-bootstrap-theme/blob/1.0/Resources/Themes/Frontend/BootstrapBare/frontend/register/shipping_fieldset.tpl#L188
vs
https://github.com/shopware/shopware/blob/9a116f29f78c0005e031e34ffcce919b6a50e3a9/themes/Frontend/Bare/frontend/register/shipping_fieldset.tpl#L174

**Comment by benjamin-ott** [comment]
Thank you @shyim. I removed the condition.
