### ISSUE TITLE
Fallback variables should respect theme settings

### ISSUE THREAD

**Issue by schliflo** [conexco/shopware-bootstrap-theme#9]
https://github.com/conexco/shopware-bootstrap-theme/blob/15f37ec79d123834d359e2ce2da87009f5473e89/Resources/Themes/Frontend/BootstrapBare/frontend/_public/src/less/_variables/sw-fallback.less#L2
Looking at this file it seems that the settings made in the theme config are not respected. I suggest mapping common variables like `@swf-brand-primary` to `@brand-primary` and `@swf-brand-success` to `@highlight-success` etc... This should improve 3rd party plugin styling out of the box.

**Comment by benjamin-ott** [comment]
You're right they should. I tried to map as many variables as possible in my commit.
